#ifndef TEXTURE_CONFIG_H
#define TEXTURE_CONFIG_H

#define COULEUR_TEXTURE_UNIT_0          GL_TEXTURE0
#define COULEUR_TEXTURE_UNIT_IND_0      0
#define COULEUR_TEXTURE_UNIT_1          GL_TEXTURE1
#define COULEUR_TEXTURE_UNIT_IND_1      1
#define COULEUR_TEXTURE_UNIT_2          GL_TEXTURE2
#define COULEUR_TEXTURE_UNIT_IND_2      2
#define COULEUR_TEXTURE_UNIT_3          GL_TEXTURE3
#define COULEUR_TEXTURE_UNIT_IND_3      3
#define COULEUR_TEXTURE_UNIT_4          GL_TEXTURE4
#define COULEUR_TEXTURE_UNIT_IND_4      4
#define COULEUR_TEXTURE_UNIT_5          GL_TEXTURE5
#define COULEUR_TEXTURE_UNIT_IND_5      5


#endif
