#pragma once

#define COULEUR_TEXTURE_UNIT              GL_TEXTURE0
#define COULEUR_TEXTURE_UNIT_IND        0
#define OMBRE_TEXTURE_UNIT             GL_TEXTURE1
#define OMBRE_TEXTURE_UNIT_IND       1
#define NORMAL_TEXTURE_UNIT             GL_TEXTURE2
#define NORMAL_TEXTURE_UNIT_IND       2
#define RANDOM_TEXTURE_UNIT             GL_TEXTURE3
#define RANDOM_TEXTURE_UNIT_IND       3
#define DISPLACEMENT_TEXTURE_UNIT       GL_TEXTURE4
#define DISPLACEMENT_TEXTURE_UNIT_IND 4
#define MOTION_TEXTURE_UNIT             GL_TEXTURE5
#define MOTION_TEXTURE_UNIT_IND       5
#define EXPOSANT_SPECULAIRE_UNIT             GL_TEXTURE6
#define EXPOSANT_SPECULAIRE_UNIT_IND       6
#define DETAIL_MAP_TEXTURE_UNIT                     GL_TEXTURE7
#define DETAIL_MAP_TEXTURE_UNIT_IND               7
